language: node_js
node_js:
  - "14"
script:
  - gatsby build
  - echo 'csv.js.org' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: public
  on:
    branch: master
env:
  global:
  - secure: "VeKBHR0nBnApYZuzSLrVTMdmxG57BaiDRutcLOq0gai/rKugl3YvVs9qHGauWfGN7RbY2EAaoUEUGXs8d03po4mXrNje38NwRoiD1hF9jLiqEkeoWIsOtai9hNpmY3IhPl6ySNW+enWksjjHOCLDIjkzVnL4mMV6TsBTonSaYd4="
